name: Build
on:
  release:
    types:
      - published
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}}
      - id: buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          build-args: SOURCE=https://github.com/${{ github.repository }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
